server:
  port: 5000


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://ec2-54-160-145-160.compute-1.amazonaws.com:8761/eureka/,http://localhost:8761/eureka/,http://Discovery-Service:8761/eureka/
spring:
  application:
    name: "Discovery-Service"